- examples/example_3D_trajectories.py
- src/mrinufft/__init__.py
- src/mrinufft/trajectories/__init__.py
- src/mrinufft/trajectories/trajectory3D.py
This PR adds two trajectories, with corresponding documentation & examples:
- Seiffert spirals, also known as Yarnball: quite recent analytical trajectories that rely on Jacobi elliptic functions and radially modulated Seiffert spirals to keep the gradient norm constant at a given radius.
- Seiffert shells, an exclusive trajectory using more conventional Seiffert spirals, i.e. defined over sphere surfaces and providing curves with constant speed and angular velocity. This trajectory is structured into concentric sphere similarly to helical and annular shells added previously.
> Add Seiffert spiral and shell trajectories

- README.rst
- docs/conf.py
- docs/index.rst
- examples/example_display_config.py
- src/mrinufft/trajectories/display.py
This PR does two things: 
1. It adds convenient api to update the displayConfig temporarily with a context manager 
2. Add support for custom color cycling by sampling existing matplotlib colormap.
> Improve the display config

- .github/workflows/test-ci.yml
- examples/example_density.py
- src/mrinufft/__init__.py
- src/mrinufft/_utils.py
- src/mrinufft/density/__init__.py
- src/mrinufft/density/geometry_based.py
- src/mrinufft/density/nufft_based.py
- src/mrinufft/density/utils.py
- src/mrinufft/operators/__init__.py
- src/mrinufft/operators/base.py
- src/mrinufft/operators/interfaces/bart.py
- src/mrinufft/operators/interfaces/cufinufft.py
- src/mrinufft/operators/interfaces/finufft.py
- src/mrinufft/operators/interfaces/gpunufft.py
- src/mrinufft/operators/interfaces/sigpy.py
- src/mrinufft/operators/stacked.py
- tests/test_density.py
This PR allow to dispatch the choice for density compensation estimation. It also provides a `get_density` methods and can show which density compensation methods are available. 
Also, It provides a generic purpose `MethodRegister` that could be used for registering other collection of methods (trajectories functions for example).
> Dispatch density methods in operators

- examples/example_density.py
- src/mrinufft/density/nufft_based.py
- src/mrinufft/operators/base.py
- src/mrinufft/operators/interfaces/gpunufft.py
- tests/test_batch.py
I guess after this we are ready for a release.
> Some fixes for pipe density

- docs/api.rst
- docs/misc/contributors.rst
- pyproject.toml
- src/mrinufft/io/cfl.py
- src/mrinufft/io/nsp.py
- src/mrinufft/operators/interfaces/gpunufft.py
various improvements for the doc.
> Doc improvements

- src/mrinufft/density/geometry_based.py
Voronoi density compensation may have some trouble estimating area/volumes of cell that are on boundary, this PR removes the outliers and uses interpolation to fix values.
> fix: robust voronoi estimation.

- examples/example_gif_2D.py
- examples/example_gif_3D.py
This PR add two examples to produces GIF showcasing the differents trajectories in MRI-NUFFT. 
It is based on the code of @Daval-G, with some speedup using joblib and PIL. 
There was some trick to have the gif rendered in the gallery properly (see the `#sphinx_gallery_start_ignore` block in the examples)
> feat: add examples creating GIF of trajectories.

- .github/workflows/style.yml
- .github/workflows/test-ci.yml
> feat(ci): add cache capabilities.

- src/mrinufft/operators/base.py
add 
https://github.com/mind-inria/mri-nufft/blob/504426774146b209ea7fb2f67133022a04748dbb/src/mrinufft/operators/base.py#L344-L349
> add method == true in base.py

- pyproject.toml
- src/mrinufft/io/nsp.py
- src/mrinufft/io/siemens.py
- src/mrinufft/io/utils.py
This PR solves #153 by moving from [mapVBVD](https://github.com/wtclarke/pymapvbvd) to [twixtools](https://github.com/pehses/twixtools) to read Siemens Twix scan files and storing the orientation matrix in the `hdr` dict.
> Twixtools and orientation matrix extraction

- docs/conf.py
- examples/GPU/example_cg.py
- examples/README.rst
- examples/conftest.py
- examples/example_2D_trajectories.py
- examples/example_3D_trajectories.py
- examples/example_display_config.py
- examples/example_gif_2D.py
- examples/example_gif_3D.py
- examples/example_learn_samples_multires.py
- examples/example_offresonance.py
- examples/example_readme.py
- examples/example_stacked.py
- examples/example_trajectory_tools.py
- examples/utils.py
This PR cleans the CPU examples in several ways:
- Change brain orientations to the medical standard
- Reduce blank spaces around images
- Remove some overlaps in figures
- Split script-specific code from the utils and data preparation
- Homogeneize parts and subparts names & structures
- Homogeneize one-line descriptions
- Homogeneize capitalizations, punctuations
- Apply isort to clean imports
- Fix a bunch of typos
- Fix paragraph irregularities
- Fix a few cross references
- Break lines sometimes
- Remove a few dead parts
- Remove many useless outputs
- Remove references to MFI in off-resonance operator (we don't do MFI but the opposite)
I will try to do the same for GPU examples later. Note that trajectory examples are barely touched, not because they are perfect but the opposite as …
> Clean CPU examples

- docs/nufft.rst
- examples/example_subspace.py
- src/mrinufft/extras/__init__.py
- src/mrinufft/extras/data.py
- src/mrinufft/extras/field_map.py
- src/mrinufft/extras/sim.py
- src/mrinufft/operators/__init__.py
- src/mrinufft/operators/subspace.py
- tests/case_trajectories.py
- tests/operators/test_subspace.py
This PR add a new extension to enable low rank subspace projected NUFFT as described (in a Cartesian context) [here](https://onlinelibrary.wiley.com/doi/10.1002/mrm.26102). A non-exhaustive list potential applications is:
- Multi-contrast MRI with virtual echoes (e.g., [Tamir et al.](https://onlinelibrary.wiley.com/doi/10.1002/mrm.26102))
- Acceleration of iterative reconstruction for quantitative MRI (e.g., Magnetic Resonance Fingerprinting, MR Multitasking)
- Dynamic (e.g., cardiac) MRI
> [feature] add subspace projection model.

- src/mrinufft/trajectories/display.py
- src/mrinufft/trajectories/gradients.py
- src/mrinufft/trajectories/inits/random_walk.py
- src/mrinufft/trajectories/inits/travelling_salesman.py
- src/mrinufft/trajectories/maths/fibonacci.py
- src/mrinufft/trajectories/maths/primes.py
- src/mrinufft/trajectories/maths/rotations.py
- src/mrinufft/trajectories/maths/tsp_solver.py
- src/mrinufft/trajectories/sampling.py
- src/mrinufft/trajectories/tools.py
- src/mrinufft/trajectories/trajectory2D.py
- src/mrinufft/trajectories/trajectory3D.py
- src/mrinufft/trajectories/utils.py
Just cleaning the documentation a bit and adding type hints
> Clean documentation and add type hints

- examples/GPU/example_fastMRI_UNet.py
- examples/GPU/example_learn_samples.py
- examples/GPU/example_learn_samples_multicoil.py
- examples/example_learn_samples_multires.py
- examples/example_trajectory_tools.py
- src/mrinufft/trajectories/__init__.py
- src/mrinufft/trajectories/display.py
- src/mrinufft/trajectories/tools.py
- src/mrinufft/trajectories/utils.py
This PR adds random sampling extension for trajectories. 
In particular, it adds a trajectory expansion function (`stack_random`) to stack 2D trajectory following a certain distribution.
- ~~([ ] Add ND sampling (e.g poisson disc))~~
An example of stack of spiral with uniform sampling (but fully sampled in the center of k-space)
> Random sampling

- src/mrinufft/trajectories/__init__.py
- src/mrinufft/trajectories/display.py
- src/mrinufft/trajectories/display3D.py
- src/mrinufft/trajectories/tools.py
Minor PR to fix the "signal" display for gradient diagrams, that was needlessly complex and not even properly representing signal as intended.
Old display
New display
> Clean signal gradient display

- src/mrinufft/trajectories/sampling.py
This PR fixes the coordinates fitted by the Lloyd sampling algorithm. As shown in the image below, each voxel was shifted by half a voxel width which lead to errors when gridding the locations for example. The new fitted coordinates correspond to what was already done for the random sampling, making both behaviors match.
> Fix Lloyd's sampling coordinates

- src/mrinufft/io/siemens.py
- src/mrinufft/io/utils.py
This PR adds a nifti_affine function which expands on siemens_quat_to_rot_mat to include scaling and offset.
The affine matrix is usually used by preprocessing and analysis software and it is crucial for registration for example or any step that expect to apply the matrix and get milimeter coordinates.
The offset in this fuction will usually be wrong by 1/2 of 1 voxel size, from the test I did I couldn't figure out a pattern.
> Nifti affine matrix

- src/mrinufft/operators/off_resonance.py
This PR adds a negate flag to allow switching the sign of the field map in off-resonance correction, addressing issue [#254](https://github.com/mind-inria/mri-nufft/issues/254).
Default remains backward-compatible (negate=True)
If negate=False, the phase factor uses a + sign (conventional)
>  Fix : add negate flag to switch sign convention in ORC

- pyproject.toml
- src/mrinufft/operators/interfaces/cufinufft.py
- src/mrinufft/operators/interfaces/gpunufft.py
- Solves #289
This PR adds support for selecting the CUDA device using `gpu_device_id` in both `cufinufft` and `gpunufft` operators:
-  Adds optional `gpu_device_id` to kwargs
- Sets cupy cuda device in cufinufft constructor.
- Passes `gpu_device_id` to gpunufft's NUFFTOp (compatible with recent changes in gpuNUFFT https://github.com/chaithyagr/gpuNUFFT/pull/26)
Usage example: 
<pre>``` import mrinufft 
import numpy as np
nufft = mrinufft.get_operator(
backend_name="cufinufft", wrt_data=True, wrt_traj=False
)(
samples=np.random.rand(100,3),
shape=(20,20,20),
density="pipe",
squeeze_dims=False,
gpu_device_id=1
)``` </pre>
If the specified gpu_device_id is invalid, a warning will be issued like:
`Failed to set CUDA device 1: cudaErrorInvalidDevice: invalid device ordinal`
and the code will …
> Added support for multi-GPU runs with extra optional  in kwargs for both cufinufft and gpunufft operators

- examples/GPU/example_3d_trajectory_display.py
- examples/operators/example_offresonance.py
- examples/trajectories/example_3D_trajectories.py
- examples/trajectories/example_display_config.py
- examples/trajectories/utils.py
- src/mrinufft/io/nsp.py
- src/mrinufft/trajectories/display.py
- src/mrinufft/trajectories/display3D.py
- src/mrinufft/trajectories/tools.py
- src/mrinufft/trajectories/utils.py
- tests/test_io.py
This PR introduces an Acquisition Configuration class, to help manage physical units relevant to MR system.
- Closes #282
- Closes #257
- Open a clean path to #272, and all hardware dependent trajectories.
- There are some conflict with #283 , I will take care of it once we know which PR goes first.
Changes proposed in this pull request:
- Introduce the Acquisition class
- Update most of the functions (notable exception: `read_trajectory` in `io.nsp` module) that were relying on parameters such as `gmax`, `smax`, `raster_time` to use the acquisition object instead. 
This is a significant change (a lot of function signatures are modified), I would recommend a new release (2.0.0, including pulseq support). 
Note also that I tried to express all physical quantities in raw SI units (a.k.a. no …
> Acquisition Configuration
